Initial addition of support for Pipfiles (Pipenv)
meain/vim-package-info pull request #18
Opened 2019-04-21 15:00 UTC by jamesl33

Initial addition of support for Pipfiles (Pipenv)

## Description

Modified parser to allow the displaying of module version info for Pipfiles (Pipenv). I have updated the README.md, however, I have omitted the addition of an screenshot so that @meain can add one (keeping the colour scheme uniform); I also don't have an Imgur account.

## Testing

Where I have modified anything not related to Pipfiles, I have checked to ensure that previous supported filetypes still function as expected.

I have also added an example Pipfile which can be viewed [here](https://github.com/jamesl33/vim-package-info/blob/pipfile-support/examples/Pipfile).

2019-04-22 13:20 UTC, meain requested changes
Hey @jamesl33 , thanks a lot for the PR. Looks good, just a few things.

I see two dependencies which are having some issues.

```
tvdb-api = ">=2.0"
imdbpy = ">=6.6"
```

The first one `tvdb-api` is because the link seems to redirect it to `tvdb_api` (underscore) and the current fetching script does not take care of redirects. I will change out the code used to fetch the api response to support redirects and that should fix it.

The other one is `imdbpy`. The issue I think that is happening here is that it in PyPI is spelt `IMDbPY`. Not sure how to handle that one right now, but I guess we will just open an issue and skip it for now.

2019-04-22 13:20 UTC, meain commented on rplugin/node/vim-package-info/parser.js
> +    return verinfo.match(/(\d+\.)?(\d+\.)?(\*|\d+)/)[0];
I guess we could return the whole thing here and just strip out the extra stuff in `diff.js`.

In the future I am planning to add support for finding the latest version you can update based on the current version. Things like specifiers for stick to current major version and stuff like that.

If you see we are actually doing something similar right now in `diff.js`, well just removing the first char. But I guess you get the idea.

So could you change the stripping of `>=` to `diff.js`

2019-04-22 13:33 UTC, meain commented
Actually even the `imdbpy` issue was solved from adding redirects. You could merge the new master and it should be good to go.

2019-04-22 14:54 UTC, jamesl33 commented
Thank you for the feedback, I have rebased the commit and I believe that I have address the feedback from [this](https://github.com/meain/vim-package-info/pull/18#discussion_r277286584) comment.

2019-04-22 14:57 UTC, jamesl33 commented
> Thank you for the feedback, I have rebased the commit and I believe that I have address the feedback from [this](https://github.com/meain/vim-package-info/pull/18#discussion_r277286584) comment.

Oh I do apologise, I missed that you committed the changes to *my* repository, I didn't know you could do that. I will update to include your commits.

2019-04-22 17:37 UTC, meain commented
Hey, I decided to add testing just so as to make sure new ones don't break support for any any old filetypes. So could you please add tests for `Pipfile`?

2019-04-22 20:09 UTC, jamesl33 commented
Hi, sounds like it was a good idea too me. I rebased the commit again and added testing as requested.

2019-04-23 04:27 UTC, meain commented
Awesome, thanks a lot!

2019-04-23 04:27 UTC, merged