Generalize the key off the name of the file, and add pyproject.toml s…
meain/vim-package-info pull request #19
Opened 2019-04-22 12:44 UTC by DanCardin

…upport.

2019-04-22 13:43 UTC, meain reviewed
Hey @DanCardin , thank you for the PR. I think it is good idea to change the way the filename check is done and I think we would have needed the depSelector logic at some point of time.

I will merge this in as soon as the `Pipfile` PR has been merged.

2019-04-22 13:43 UTC, meain commented on rplugin/node/vim-package-info/utils.js
> +  if (filename.match(/^project.json$/)) {
it is `package.json`
```suggestion
  if (filename.match(/^package.json$/)) {
```

2019-04-22 14:03 UTC, DanCardin commented
I'll definitely need to fix/rebase from the Pipfile changes so i'll await that.

For now the depSelector logic seems fairly innocuous, given the currently supported types of things, but at some point it seems like the filetypes should probably grow individual handlers, because `.split('.')` is really only going to work correctly for toml files. I felt mildly bad putting it there, but I figured that could happen later.

2019-04-23 04:34 UTC, meain commented
Hey, the other PR has been merged. Could you rebase with the master branch.

Also I have added some simple test for different file types, could you add test for `pyproject.toml`

2019-04-23 11:37 UTC, DanCardin commented
done and done!

2019-04-23 11:43 UTC, DanCardin commented
I tried locally running autoshot.sh but my local alacritty doesn't have a `--position` argument it seems

2019-04-23 14:48 UTC, meain requested changes
Just a few more changes and we should be good to go.

2019-04-23 14:48 UTC, meain commented on rplugin/node/vim-package-info/parser.js
> +  "python:pyproject": /([a-zA-Z0-9\-_]*) *=.*/
Have to handle when the dependency has `"` arround it.
```suggestion
  "python:pyproject": /['|"]?([a-zA-Z0-9\-_]*)['|"]? *=.*/
```

2019-04-23 14:48 UTC, meain commented on rplugin/node/vim-package-info/parser.js
> +  for (item of pathItems) {
Initialize `item`. Just keeping it tidy.

```suggestion
  for (let item of pathItems) {
```

2019-04-23 14:48 UTC, meain commented on rplugin/node/vim-package-info/parser.js
> +  "python:pyproject": /([a-zA-Z0-9\-_]*) *=.*/
Could you also add a test case for this one.

2019-04-23 14:51 UTC, meain commented
Btw, you can use this link for the image `https://i.imgur.com/s6Cu8oZ.png`.

![](https://i.imgur.com/s6Cu8oZ.png)

2019-04-23 20:15 UTC, DanCardin commented
done and done, once more

2019-04-24 05:44 UTC, meain commented
Awesome, thanks a lot ;)

2019-04-24 05:45 UTC, merged